@startuml Devine
participant Parent as "Parent\nProcess"
participant Child  as "Child\nProcess"

Parent -> Parent : srand(uptime())\nmystery = rand()%100 + 1
Parent -> Child  : write(pipe1, "GAME_START: mystery ∈ [1..100]")
activate Child

alt tant que non trouvé et coups < max
    Child -> Parent : write(pipe1, guess)
    activate Parent
    Parent -> Child : write(pipe2, result)\n// "higher" / "lower" / "found"
    deactivate Parent
    Child -> Child  : sleep(1s)
end

deactivate Child
@enduml
