@startuml OXO_Initialisation
participant Arbitre as Referee
participant JoueurA as PlayerA
participant JoueurB as PlayerB

== Création des pipes ==
note over Referee
  pipeParentToA, pipeAToParent  
  pipeParentToB, pipeBToParent
end note

== Lancement des processus ==
Referee -> PlayerA : fork()  
activate PlayerA
PlayerA --> Referee : pid1
deactivate PlayerA

Referee -> PlayerB : fork()  
activate PlayerB
PlayerB --> Referee : pid2
deactivate PlayerB

== Fermeture des descripteurs non-utilisés ==
note over Referee
  close() des extrémités inutiles
end note
@enduml
