@startuml PingPong
participant Parent as "Parent\nProcess"
participant Child  as "Child\nProcess"

loop [i = 1..N]
    Parent -> Child : write(pipe1, "ping")
    activate Child
    Child -> Parent : write(pipe2, "pong")
    deactivate Child
end
@enduml
